decoration {
# See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 5
    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = true
    }
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}


# Just ignore this
# 720p
# monitor = HDMI-A-1, 1280x720@60, 0x0, 1

# windowrule = float,^(thunar)$
# windowrule = float,^(pavucontrol)$
windowrule = size 1000 750, ^(thunar)$
windowrule = move 20%, ^(thunar)$

# windowrulev2 = opacity 0.0 override, class:^(xwaylandvideobridge)$
# windowrulev2 = noanim, class:^(xwaylandvideobridge)$
# windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$
# windowrulev2 = maxsize 1 1, class:^(xwaylandvideobridge)$
# windowrulev2 = noblur, class:^(xwaylandvideobridge)$
