decoration {
# See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 5
    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = true
    }
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}


windowrule = float,^(thunar)$
windowrule = size 1000 750, ^(thunar)$

windowrulev2 = focusonactivate, class:.*
windowrulev2 = noblur, title:^()$, class:^()$
