decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 5
    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = true
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
 #   screen_shader = ~/.config/hypr/Shader.frag
}


# 720p
# monitor = HDMI-A-1, 1280x720@60, 0x0, 1

windowrule = float,^(qview)$
windowrule = float,^(thunar)$
windowrule = float,^(pavucontrol)$
windowrulev2 = float,class:^(qview)$

windowrule = size 1000 750, ^(thunar)$
windowrule = move 20%, ^(thunar)$
windowrule = size 900 600, ^(alacritty)$
windowrule = move 20%, ^(alacritty)$

windowrulev2 = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrulev2 = noanim, class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrulev2 = noblur, class:^(xwaylandvideobridge)$
